apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-github-runner-ecs
  description: terraform-github-runner-ecs
spec:
  type: website
  owner: user:guest
  lifecycle: experimental
